from marshmallow import Schema, fields


class BookDetailsSchema(Schema):
    ISBN = fields.Str(required=True) # book id
    Name = fields.Str()
    Description = fields.Str()
    Price = fields.Int()
    Author = fields.Str()
    Genre = fields.Str()
    Publisher = fields.Str()
    YearPublished = fields.Str()
    Sold =fields.Int()
    Rating = fields.Int()

class ProfileManagement(Schema):
    Username = fields.Str(required = True)
    Password = fields.Str(required = True)
    Name = fields.Str()
    EmailAddress = fields.Str()
    HomeAddress = fields.Str()
    CreditCardName = fields.Str()
    CreditCardNumber = fields.Str()
    CreditCardExpMonth = fields.Int()
    CreditCardExpYear = fields.Int()
    CreditCardSecurityCode = fields.Str()
    CreditCardZipCode = fields.Int()

class RatingsSchema(Schema):
    UserID = fields.Str(required = True)
    ISBN = fields.Str() # book id
    RatingDate = fields.Str()
    Rating = fields.Int()
    CommentDate = fields.Str()
    Comment = fields.Str()

class WishlistSchema(Schema):
    WishlistID = fields.Str(required=True)
    Username = fields.Str()
    ISBN0 = fields.Str()
    ISBN1 = fields.Str()
    ISBN2 = fields.Str()
    ISBN3 = fields.Str()
    ISBN4 = fields.Str()
    ISBN5 = fields.Str()
    ISBN6 = fields.Str()
    ISBN7 = fields.Str()
    ISBN8 = fields.Str()
    ISBN9 = fields.Str()
    ISBN10 = fields.Str()
    ISBN11 = fields.Str()
    ISBN12 = fields.Str()
    ISBN13 = fields.Str()
    ISBN14 = fields.Str()
    ISBN15 = fields.Str()
    ISBN16 = fields.Str()
    ISBN17 = fields.Str()
    ISBN18 = fields.Str()
    ISBN19 = fields.Str()
    ISBN20 = fields.Str()
    ISBN21 = fields.Str()
    ISBN22 = fields.Str()
    ISBN23 = fields.Str()
    ISBN24 = fields.Str()
    ISBN25 = fields.Str()
    ISBN26 = fields.Str()
    ISBN27 = fields.Str()
    ISBN28 = fields.Str()
    ISBN29 = fields.Str()