from db import db

class WishlistModel(db.Model):
    
    # Create DB columns
    WishlistID = db.Column(db.String, primary_key=True)
    Username = db.Column(db.String)
    ISBN0 = db.Column(db.String)
    ISBN1 = db.Column(db.String)
    ISBN2 = db.Column(db.String)
    ISBN3 = db.Column(db.String)
    ISBN4 = db.Column(db.String)
    ISBN5 = db.Column(db.String)
    ISBN6 = db.Column(db.String)
    ISBN7 = db.Column(db.String)
    ISBN8 = db.Column(db.String)
    ISBN9 = db.Column(db.String)
    ISBN10 = db.Column(db.String)
    ISBN11 = db.Column(db.String)
    ISBN12 = db.Column(db.String)
    ISBN13 = db.Column(db.String)
    ISBN14 = db.Column(db.String)
    ISBN15 = db.Column(db.String)
    ISBN16 = db.Column(db.String)
    ISBN17 = db.Column(db.String)
    ISBN18 = db.Column(db.String)
    ISBN19 = db.Column(db.String)
    ISBN20 = db.Column(db.String)
    ISBN21 = db.Column(db.String)
    ISBN22 = db.Column(db.String)
    ISBN23 = db.Column(db.String)
    ISBN24 = db.Column(db.String)
    ISBN25 = db.Column(db.String)
    ISBN26 = db.Column(db.String)
    ISBN27 = db.Column(db.String)
    ISBN28 = db.Column(db.String)
    ISBN29 = db.Column(db.String)